name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'

inputs:
  bucket:
    description: 'S3 bucket name'
    required: true
  region:
    description: 'S3 bucket region'
    required: false
    default: 'us-west-2'
  dist-folder:
    description: 'Path to folder containing deployable files'
    required: true

runs:
  using: 'node16'
  main: 'main.js'